//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiciosTaller.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class Reparacion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Reparacion()
        {
            this.Empleadoes = new HashSet<Empleado>();
            this.Facturas = new HashSet<Factura>();
        }
    
        public int id_reparacion { get; set; }
        public int id_tipo_reparacion { get; set; }
        public string descripcion { get; set; }
        public System.DateTime fecha_reparacion { get; set; }
        public decimal costo_reparacion { get; set; }
        public string id_vehiculo { get; set; }

        [JsonIgnore]
        public virtual Tipo_reparacion Tipo_reparacion { get; set; }
        [JsonIgnore]
        public virtual Vehiculo Vehiculo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [JsonIgnore]
        public virtual ICollection<Empleado> Empleadoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [JsonIgnore]
        public virtual ICollection<Factura> Facturas { get; set; }
    }
}
